Chat.OMEの作成
extreal-dev/Extreal.Integration.Chat.OME pull request #1
Opened 2024-02-13 08:52 UTC by sus-yoshikane-t

# 何の変更を加えましたか？

# 何を確認しましたか?

## 実装

- [x] Frameworkの誤った使い方にすぐに気づけるように、無効な引数や無効なメソッド呼び出しに対するチェックが入っていることを確認しました
- [x] Framework実行時の動きが分かるように、ログ（Error/Warn/Info/Debug）を出力していることを確認しました
- [x] 静的解析で問題が見つからないことを確認しました
- [x] フレームワーク利用者が使うAPI（主にprivate以外）に C# ドキュメントを記述しました

## テスト

- [ ] 全ての自動テストが成功することを確認しました
- [ ] テストカバレッジが100%になることを確認しました
- [ ] サンプルがあるものはサンプルが動作することを確認しました

## 変更影響

- [ ] GuideのReleaseページに変更内容が追加されることを確認しました
- [ ] GuideのModuleページ（機能ページ）に変更が反映されることを確認しました
- [ ] GuideのLearningページに変更が反映されることを確認しました
- [ ] Sample Applicationに変更が反映されることを確認しました

# レビュアーへのメッセージ

2024-02-20 11:54 UTC, sasuke9410 requested changes

2024-02-20 11:54 UTC, sasuke9410 commented on Samples~/MVS/Extreal.Integration.Chat.OME.MVS.asmdef
> +        "Extreal.Framework.Analyzer"
"Extreal.Framework.Analyzer"が入っており、
Checkタブでcheck-analyzer-existenceエラーが出ています。
これはプルリク作成時に解消するべきものでしょうか？
もしくはレビュー後の解決でもよいのでしょうか？

2024-02-20 11:54 UTC, sasuke9410 commented on Runtime/Extreal.Integration.Chat.OME.asmdef
Checkタブでcheck-analyzer-existenceエラーが出ています。
これはプルリク作成時に解消するべきものでしょうか？
もしくはレビュー後の解決でもよいのでしょうか？

2024-02-20 11:54 UTC, sasuke9410 commented on Runtime/NativeVoiceChatClient.cs
> +                if (!audioLevels.ContainsKey(localClientId) || audioLevels[localClientId] != audioLevel)
会話音量を!=で比較していますが、
float型であるため一致することはほぼないのではないかと思います。
Math.Abs(audioLevels[clientId] - audioLevel) ><float型閾値>などとするのはどうでしょうか？

262行目も同様です

2024-02-20 11:54 UTC, sasuke9410 commented on Runtime/VoiceChatClient.cs
> +using Cysharp.Threading.Tasks;
UniTaskを使用していないようなのでこのnamespaceは不要かなと思いました。

2024-02-20 11:54 UTC, sasuke9410 commented on Runtime/WebGLVoiceChatClient.cs
> +using Cysharp.Threading.Tasks;
UniTaskを使用していないようなのでこのnamespaceは不要かなと思いました。

2024-02-20 11:54 UTC, sasuke9410 commented on Runtime/NativeVoiceChatClient.cs
> +using Cysharp.Threading.Tasks;
UniTaskを使用していないようなのでこのnamespaceは不要かなと思いました。

2024-02-20 11:54 UTC, sasuke9410 commented on WebScripts~/README.md
> +﻿# @extreal-dev/extreal.integration.p2p.webrtc
extreal-dev/extreal.integration.p2p.webrtc
ではなく、
extreal-dev/extreal.integration.chat.omeでは？

2024-02-21 03:17 UTC, kiyohome approved these changes

2024-02-27 01:17 UTC, sus-yoshikane-t commented on Runtime/VoiceChatClient.cs
> +using Cysharp.Threading.Tasks;
削除しました。https://github.com/extreal-dev/Extreal.Integration.Chat.OME/pull/1/commits/e802f8eb927d0bf64a431ba3706b509effce8b04

2024-02-27 01:18 UTC, sus-yoshikane-t commented on Runtime/WebGLVoiceChatClient.cs
> +using Cysharp.Threading.Tasks;
削除しました。https://github.com/extreal-dev/Extreal.Integration.Chat.OME/pull/1/commits/e802f8eb927d0bf64a431ba3706b509effce8b04

2024-02-27 01:18 UTC, sus-yoshikane-t commented on Runtime/NativeVoiceChatClient.cs
> +using Cysharp.Threading.Tasks;
削除しました。https://github.com/extreal-dev/Extreal.Integration.Chat.OME/pull/1/commits/e802f8eb927d0bf64a431ba3706b509effce8b04

2024-02-27 01:24 UTC, sus-yoshikane-t commented on Runtime/NativeVoiceChatClient.cs
> +                if (!audioLevels.ContainsKey(localClientId) || audioLevels[localClientId] != audioLevel)
閾値が必要な場合はライブラリ側でなく、利用者側で処理してもらう方針になりました。

2024-02-28 01:02 UTC, mahaweilu commented on Samples~/MVS/Extreal.Integration.Chat.OME.MVS.asmdef
> +        "Extreal.Framework.Analyzer"
sfu.ome側と同じ対応↓ですが、レビュー後に解消するようにします。
https://github.com/extreal-dev/Extreal.Integration.SFU.OME/pull/1#discussion_r1505193847

2024-02-28 02:36 UTC, mahaweilu commented on Runtime/Extreal.Integration.Chat.OME.asmdef
sfu.ome側と同じ対応↓ですが、レビュー後に解消するようにします。
https://github.com/extreal-dev/Extreal.Integration.SFU.OME/pull/1#discussion_r1505193847

2024-02-28 02:39 UTC, mahaweilu commented on WebScripts~/README.md
> +﻿# @extreal-dev/extreal.integration.p2p.webrtc
修正しました。
[8476408](https://github.com/extreal-dev/Extreal.Integration.Chat.OME/pull/1/commits/8476408270857ee9865a1b7a443fe2ef44a12d76)

2024-02-28 09:00 UTC, sasuke9410 commented on Samples~/MVS/Extreal.Integration.Chat.OME.MVS.asmdef
> +        "Extreal.Framework.Analyzer"
理解しました、問題なしです。

2024-02-28 09:24 UTC, sasuke9410 commented on Runtime/Extreal.Integration.Chat.OME.asmdef
理解しました、問題なしです。

2024-02-28 09:24 UTC, sasuke9410 commented on Runtime/NativeVoiceChatClient.cs
> +                if (!audioLevels.ContainsKey(localClientId) || audioLevels[localClientId] != audioLevel)
了解です、問題なしです

2024-02-28 09:25 UTC, sasuke9410 commented on Runtime/WebGLVoiceChatClient.cs
> +using Cysharp.Threading.Tasks;
確認しました！

2024-02-28 09:25 UTC, sasuke9410 commented on Runtime/NativeVoiceChatClient.cs
> +using Cysharp.Threading.Tasks;
確認しました！

2024-02-28 09:25 UTC, sasuke9410 commented on WebScripts~/README.md
> +﻿# @extreal-dev/extreal.integration.p2p.webrtc
確認しました！

2024-02-28 09:25 UTC, sasuke9410 approved these changes

2024-02-28 09:26 UTC, sasuke9410 commented on Runtime/VoiceChatClient.cs
> +using Cysharp.Threading.Tasks;
確認しました！

2024-02-29 08:20 UTC, merged